### ISSUE TITLE
-n option not available

### ISSUE THREAD

**Issue by guidozuc** [ielab/inst_eval#1]
![image (4)](https://user-images.githubusercontent.com/6101372/97579172-77ca3580-1a3d-11eb-87d8-3e7790bc1ba3.png)

**Comment by guidozuc** [comment]
The problem is on the lines:
```            
score_min = inst_algorithm(T, ranked_gains, len(results[qId]), 0.0) if len(ranked_gains) > 0 else 0.000 # assume unjudged are all not relevant
score_max = inst_algorithm(T, ranked_gains, len(results[qId]), 1.0) if len(ranked_gains) > 0 else 0.000 # assume unjudged are all relevant
```

of inst_eval.py

@hanglics to fix.

**Comment by guidozuc** [comment]
@hanglics remember to fix the help function accordingly, i.e. follow the readme

**Comment by hanglics** [comment]
Finished fixing the -n option and added the -q option to turn on/off printing per query results, default is off, which only show the results of "all".

**Comment by hanglics** [comment]
But there is another bug in the algorithm, it does not check if the n value is larger than the length of ranked list or not, if user pass in 1000 as -n, the ranked list is only 900, it will break the program, I can add logic to check n, if n > len(ranked_list) then n = len(ranked_list) but in this case the inst eval_depth is no longer 1000. Do you have any suggestions?

**Comment by bevankoopman** [comment]
Can you please post the contents of `inst_eval` script from the example command line? Is this the python script to shell pointer to it?

**Comment by bevankoopman** [comment]
Guys, I think something is not correct with either the inst_eval version you have or how you call it. 

I downloaded your qrels (`pass-qrels.msmarco-dev.small.tsv`) and rankings (`pass-dev-qljm.small.txt`). Then I ran:

```python
python inst_eval.py -n 1 -T 1 pass-qrels.msmarco-dev.small.tsv pass-dev-qljm.small.txt
```

Takes a while to run and I get the results:

```
num_q		all	6980
num_ret		all	999
num_rel		all	1
num_rel_ret	all	0
inst_min	all	0.0584
inst_max	all	1.0000
inst_res	all	0.9416
```

**Comment by hanglics** [comment]
Yes, `-n 1` works fine, but when I pass in `-n 1000` it breaks.
