### ISSUE TITLE
-T OVER_WRITE_T does not work

### ISSUE THREAD

**Issue by guidozuc** [ielab/inst_eval#2]

**Comment by bevankoopman** [comment]
Was this fixed @hanglics?

**Comment by hanglics** [comment]
No I dont believe so, I only added a -q option here.

**Comment by bevankoopman** [comment]
Updated to make setting T mutually exclusive via:
`usage: inst_eval.py [-h] [-c] [-n EVAL_DEPTH] [-q] (-tpq T_PER_QUERY | -T OVER_WRITE_T)
                    trec_qrel_file trec_results_file`
